// Code generated by genschema; DO NOT EDIT

package row

import (
	"time"
)

// IsubataMessage is table `isubata_message`.
// ISUBATA メッセージ
type IsubataMessage struct {

	// katsubushi
	ID int64 `json:"id" schema:"id"`

	// =isubata_channel.id
	ChannelID int64 `json:"channel_id" schema:"channel_id"`

	// =isubata_user.id
	UserID int64 `json:"user_id" schema:"user_id"`

	// 本文
	Content string `json:"content" schema:"content"`

	// CreatedAt is column `created_at`.
	CreatedAt time.Time `json:"created_at" schema:"created_at"`

	// related to IsubataUser(1:1) * DBにないフィールドはジェネレータに設定を書いて追加している
	IsubataUser *IsubataUser `json:"-" schema:"-"`

	// RefetchForUpdateされたrowであるかのフラグ
	IsForUpdate bool `json:"-" schema:"-"`
}
