// Code generated by genschema; DO NOT EDIT

package row

import (
	"time"
)

// IsubataUser is table `isubata_user`.
// ISUBATA ユーザー
type IsubataUser struct {

	// katsubushi
	ID int64 `json:"id" schema:"id"`

	// アカウント名
	Name string `json:"name" schema:"name"`

	// salt
	Salt string `json:"salt" schema:"salt"`

	// パスワード
	Pass string `json:"pass" schema:"pass"`

	// 表示名
	DisplayName string `json:"display_name" schema:"display_name"`

	// アイコンURL
	AvatarIcon string `json:"avatar_icon" schema:"avatar_icon"`

	// CreatedAt is column `created_at`.
	CreatedAt time.Time `json:"created_at" schema:"created_at"`

	// RefetchForUpdateされたrowであるかのフラグ
	IsForUpdate bool `json:"-" schema:"-"`
}
