// Code generated by genschema; DO NOT EDIT

package row

import (
	"time"
)

// IsubataChannel is table `isubata_channel`.
// ISUBATA チャンネル
type IsubataChannel struct {

	// katsubushi
	ID int64 `json:"id" schema:"id"`

	// ルーム名
	Name string `json:"name" schema:"name"`

	// UpdatedAt is column `updated_at`.
	UpdatedAt time.Time `json:"updated_at" schema:"updated_at"`

	// CreatedAt is column `created_at`.
	CreatedAt time.Time `json:"created_at" schema:"created_at"`

	// RefetchForUpdateされたrowであるかのフラグ
	IsForUpdate bool `json:"-" schema:"-"`
}
